script:
- "./build.sh"
- "mv ./.build ./build"
deploy:
  provider: releases
  api_key:
    secure: LZ1Jb1vz+V2OZjfi+MbS/wCV8n9qAJQkKUIf5nik6S+R0kwoIH/Myywk+CA5YUlnClOfbqxeHjLIJwZzuqeGWA+vwzNh3E+pUA8bfnGFco2ki438wAy9KXOgC5Sev+Nni0QyfbtnVauvAZ+YlO8/k6kLiYUlIVZhxju5SOPzTWSToomcAJEaZaRqWxgaFkOQBxLGV8VaBt+eDU0bfgiCRsChT7ZGYiZPafeM+wrGnywlLsqwX9x9XQlxwIYjdHiKyA3A+rqrkGryjRi05m7mvOCqPiYZTv7tvZY+Cn2KfCydFwPUzW6Nr8BBx1mbrIBIW51UyFGDlq2gb2PQUyxxn/GM4kFdLBe3Seqw/9w+MURI6En8boR7P/UebPWwZ3VIhPiaXe1N9minvD3Z2j4yhBiwHwoTHJb3G+z1KZGFiHR9Za0mLJ7kKeLQ0j6ZLIx36ZzdGDC02nD0C75nQ+0VNa+lU0RihJBpytS4Gf25SYtmhl50wpRXue9Z4QGcxghs7R9bg5yEvN/btcKIKssaWsAaGZ2HitAGmep5TrZ4yM7cNzqJR8zYrUjwqeIuxz2X79oTQi98LZCLw9P/pc5pnsVqbmnY1/B3/7tTi/Fd9Muqu73cK8gDpdHU9FfXGGdvqTX9shzAR47lb0HmH+JdTKbP9CHiCWxHb2If7K579KI=
  file: 
    - "./build/app.asar"
    - "./build/builds/linux/linux.zip"
    - "./build/builds/mac/mac.zip"
    - "./build/builds/win/win.zip"
  on:
    repo: nemanjan00/instagram-chat
